services:
  switch-duyetct:
    image: ghcr.io/tdngan/switch-duyetct:1.0.0
    container_name: switch-duyetct
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    init: true
